resilience4j:
  circuitbreaker:
    instances:
      helloRep:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
  retry:
    instances:
      helloRep:
        registerHealthIndicator: true
        maxRetryAttempts: 3
        waitDuration: 10s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
#          -
#          -
        ignoreExceptions:
management:
  health:
    circuitbreakers:
      enabled: true
    ratelimiter:
      enabled: true
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true