resilience4j:
  circuitbreaker:
    instances:
      helloRep:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
  retry:
    instances:
      helloRep:
        maxRetryAttempts: 3
        waitDuration: 10s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          -
          -
        ignoreExceptions:
          -